import plotter.colors as colors
style = {
    "L": {
        "name": "Local",
        "color": "black",
        "alpha": 1,
        "marker": "o",
        "linestyle": "-",
    },
    "R_[1.0, 0.0, 0.0]": {
        "name": "R - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 1,

        "marker": "s",
        "linestyle": "-",
    },
    "R_[0.0, 1.0, 0.0]": {
        "name": "R - water",
        "color": colors.color_blind_palette[4],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "R_[0.0, 0.0, 1.0]": {
        "name": "R - land",
        "color": colors.color_blind_palette[3],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "R_[0.333, 0.333, 0.334]": {
        "name": "R - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "RP_[1.0, 0.0, 0.0]": {
        "name": "R - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 1,

        "marker": "s",
        "linestyle": "-",
    },
    "RP_[0.0, 1.0, 0.0]": {
        "name": "R - water",
        "color": colors.color_blind_palette[4],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "RP_[0.0, 0.0, 1.0]": {
        "name": "R - land",
        "color": colors.color_blind_palette[3],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "RP_[0.333, 0.333, 0.334]": {
        "name": "R - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[1.0, 0.0, 0.0]_dt4": {
        "name": "T (dt4) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 1.0, 0.0]_dt4": {
        "name": "T (dt4) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 0.0, 1.0]_dt4": {
        "name": "T (dt4)- land",
        "color": colors.color_blind_palette[3],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.333, 0.333, 0.334]_dt4": {
        "name": "T (dt4) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[1.0, 0.0, 0.0]_dt12": {
        "name": "T (dt12) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 1.0, 0.0]_dt12": {
        "name": "T (dt12) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 0.0, 1.0]_dt12": {
        "name": "T (dt12) - land",
        "color": colors.color_blind_palette[3],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.333, 0.333, 0.334]_dt12": {
        "name": "T (dt12) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[1.0, 0.0, 0.0]_dt24": {
        "name": "T (dt24) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 1.0, 0.0]_dt24": {
        "name": "T (dt24) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 0.0, 1.0]_dt24": {
        "name": "T (dt24) - land",
        "color": colors.color_blind_palette[3],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.333, 0.333, 0.334]_dt24": {
        "name": "T (dt24) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[1.0, 0.0, 0.0]_dt48": {
        "name": "T (dt48) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 1.0, 0.0]_dt48": {
        "name": "T (dt48) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.0, 0.0, 1.0]_dt48": {
        "name": "T (dt48) - land",
        "color": colors.color_blind_palette[3],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TP_[0.333, 0.333, 0.334]_dt48": {
        "name": "T (dt48) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[1.0, 0.0, 0.0]_dt4": {
        "name": "TR (dt4) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 1.0, 0.0]_dt4": {
        "name": "TR (dt4) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 0.0, 1.0]_dt4": {
        "name": "TR (dt4)- land",
        "color": colors.color_blind_palette[3],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.333, 0.333, 0.334]_dt4": {
        "name": "TR (dt4) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 0.4,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[1.0, 0.0, 0.0]_dt12": {
        "name": "TR (dt12) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 1.0, 0.0]_dt12": {
        "name": "TR (dt12) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 0.0, 1.0]_dt12": {
        "name": "TR (dt12) - land",
        "color": colors.color_blind_palette[3],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.333, 0.333, 0.334]_dt12": {
        "name": "TR (dt12) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 0.6,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[1.0, 0.0, 0.0]_dt24": {
        "name": "TR (dt24) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 1.0, 0.0]_dt24": {
        "name": "TR (dt24) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 0.0, 1.0]_dt24": {
        "name": "TR (dt24) - land",
        "color": colors.color_blind_palette[3],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.333, 0.333, 0.334]_dt24": {
        "name": "TR (dt24) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 0.8,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[1.0, 0.0, 0.0]_dt48": {
        "name": "TR (dt48) - carbon",
        "color": colors.color_blind_palette[6],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 1.0, 0.0]_dt48": {
        "name": "TR (dt48) - water",
        "color": colors.color_blind_palette[4],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.0, 0.0, 1.0]_dt48": {
        "name": "TR (dt48) - land",
        "color": colors.color_blind_palette[3],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    "TRP_[0.333, 0.333, 0.334]_dt48": {
        "name": "TR (dt48) - mix",
        "color": colors.color_blind_palette[2],
        "alpha": 1,
        "marker": "s",
        "linestyle": "-",
    },
    
    



}